workspace(name = "example_repo")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "778197e26c5fbeb07ac2a2c5ae405b30f6cb7ad1f5510ea6fdac03bded96cc6f",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    # You can control the prefix of the repositories that contain the
    # wheels. With a prefix of "pypi_" the library for <requirement>
    # will be @pypi_<requirement>//:pkg.
    repo_prefix = "pypi_",
    requirements_lock = "//:requirements_lock.txt",
)

load("@pip_parsed_deps//:requirements.bzl", "install_deps")

install_deps()
