workspace(name = "rules_python_py_proto_library_example")

# The following local_path_override is only needed to run this example as part of our CI.
local_repository(
    name = "rules_python",
    path = "../..",
)

# When not using this example in the rules_python git repo you would load the python
# rules using http_archive(), as documented in the release notes.

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

# We install the rules_python dependencies using the function below.
py_repositories()

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

# Then we need to setup dependencies in order to use py_proto_library
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
    name = "rules_proto",
    sha256 = "904a8097fae42a690c8e08d805210e40cccb069f5f9a0f6727cf4faa7bed2c9c",
    strip_prefix = "rules_proto-6.0.0-rc1",
    url = "https://github.com/bazelbuild/rules_proto/releases/download/6.0.0-rc1/rules_proto-6.0.0-rc1.tar.gz",
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()


http_archive(
    name = "com_google_protobuf",
    # sha256 = "8632d7e8a6cbbd7e58f40e3f62fed77bff3df6e4dcac73498f0a68ba5a38d892",
    strip_prefix = "protobuf-d1c5e885b7b7d3ac888e89cf4d45cb0c9fa6b4ed",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/d1c5e885b7b7d3ac888e89cf4d45cb0c9fa6b4ed.tar.gz"],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps", "protobuf_register_toolchains")
protobuf_deps()
protobuf_register_toolchains()

