workspace(name = "rules_python_pip_install_simple_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "c6966ec828da198c5d9adbaa94c05e3a1c7f21bd012a0b29ba8ddbccb2c93b0d",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.1.1.tar.gz",
    ],
)

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    # See @rules_python//:examples/pip_install/BUILD for complete example of how to use this
    # repository rule.
    requirements = "//:requirements.txt",
)
