local_repository(
    name = "rules_python",
    path = "../../..",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

load("@rules_python//python:repositories_deps.bzl", "py_repositories_deps")

py_repositories_deps()

# This call is included in `py_repositories` and we are calling
# `pip_install_dependencies` only to ensure that we are not breaking really old
# code.
#
# TODO @aignas 2024-06-23: remove this before 1.0.0
load("@rules_python//python/pip_install:repositories.bzl", "pip_install_dependencies")

pip_install_dependencies()

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip_empty",
    python_interpreter_target = "@python39_host//:python",
    requirements_lock = "//empty:requirements.txt",
)

load("@pip_empty//:requirements.bzl", "install_deps")

install_deps()
