# Copyright 2024 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Create a repository to hold a local Python toolchain."""

load("//python/private:toolchains_repo.bzl", "get_host_os_arch")
load(":repo_utils.bzl", "REPO_DEBUG_ENV_VAR", "repo_utils")

_TOOLCHAIN_IMPL_TEMPLATE = """\
# Generated by python/private/local_runtime_repo.bzl

load("@rules_python//python:py_runtime.bzl", "py_runtime")
load("@rules_python//python:py_runtime_pair.bzl", "py_runtime_pair")
load("@rules_python//python/cc:py_cc_toolchain.bzl", "py_cc_toolchain")
load("@rules_python//python/private:py_exec_tools_toolchain.bzl", "py_exec_tools_toolchain")

cc_library(
    name = "python_headers",
    srcs = glob(["include/**/*.h"]),
    includes = ["include"],
)

cc_library(
    name = "libpython",
    # Don't use a recursive glob because the lib/ directory usually contains
    # a subdirectory of the stdlib -- lots of unrelated files
    srcs = glob([
        "lib/*{lib_ext}",  # Match libpython*.so
        "lib/*{lib_ext}*",  # Also match libpython*.so.1.0
    ]),
    hdrs = [":python_headers"],
)

py_runtime(
    name = "py3_runtime",
    interpreter_path = "{interpreter_path}",
    python_version = "PY3",
    interpreter_version_info = {{
        "major": "{major}",
        "minor": "{minor}",
        "micro": "{micro}",
    }},
    implementation_name = "{implementation_name}",
)

py_runtime_pair(
    name = "python_runtimes",
    py2_runtime = None,
    py3_runtime = ":py3_runtime",
)

py_exec_tools_toolchain(
    name = "py_exec_tools_toolchain",
)

py_cc_toolchain(
    name = "py_cc_toolchain",
    headers = ":python_headers",
    libs = ":libpython",
    python_version = "{major}.{minor}.{micro}",
)

alias(
    name = "os",
    actual = "{actual_os}",
)

alias(
    name = "python_version",
    actual = "{python_version}",
)
"""

_GET_INFO_PROGRAM = """
import sys
import sysconfig
import json

data = {
  "major": sys.version_info.major,
  "minor": sys.version_info.minor,
  "micro": sys.version_info.micro,
  "include": sysconfig.get_path("include"),
  "implementation_name": sys.implementation.name,
}

config_vars = [
    "LDLIBRARY", "LIBDIR", "INSTSONAME", "LIBDEST", "PY3LIBRARY",
    "SHLIB_SUFFIX",
]
data.update(zip(config_vars, sysconfig.get_config_vars(*config_vars)))
print(json.dumps(data))
"""

def _local_runtime_repo_impl(rctx):
    interpreter_path = resolve_interpreter_path(rctx, rctx.attr)
    if not interpreter_path or not interpreter_path.exists:
        fail("Unable to find interpreter from {}".format(rctx.attr.interpreter_path))

    rctx.file("getinfo.py", _GET_INFO_PROGRAM)
    output = repo_utils.execute_checked_stdout(
        rctx,
        op = "local_runtime_repo.GetPythonInfo({})".format(rctx.name),
        arguments = [
            interpreter_path,
            rctx.path("getinfo.py"),
        ],
        quiet = True,
    )
    rctx.delete("getinfo.py")
    info = json.decode(output)

    # The cc_library.includes values have to be non-absolute paths, otherwise
    # the toolchain will give an error. Work around this error by making them
    # appear as part of this repo.
    rctx.symlink(info["include"], "include")

    shared_lib_names = [
        info["PY3LIBRARY"],  # libpython3.so
        info["LDLIBRARY"],  # libpython3.11.so
        info["INSTSONAME"],  # libpython3.11.so.1.0
    ]

    # It's not entirely clear how to get the directory with libraries.
    # There's several types of libraries with different names and a plethora
    # of settings.
    # https://stackoverflow.com/questions/47423246/get-pythons-lib-path
    # For now, it seems LIBDIR has what is needed, so just use that.
    shared_lib_dir = info["LIBDIR"]

    # The specific files are symlinked instead of the whole directory
    # because it can point to a directory that has more than just
    # the Python runtime shared libraries, e.g. /usr/lib, or a Python
    # specific directory with pip-installed shared libraries.
    rctx.report_progress("Symlinking external Python shared libraries")
    for name in shared_lib_names:
        origin = rctx.path("{}/{}".format(shared_lib_dir, name))

        # The reported names don't always exist; it depends on the particulars
        # of the runtime installation.
        if origin.exists:
            rctx.symlink(origin, "lib/" + name)

    rctx.file("WORKSPACE", "")
    rctx.file("MODULE.bazel", "")
    rctx.file("REPO.bazel", "")
    rctx.file("BUILD.bazel", _TOOLCHAIN_IMPL_TEMPLATE.format(
        major = info["major"],
        minor = info["minor"],
        micro = info["micro"],
        interpreter_path = interpreter_path,
        lib_ext = info["SHLIB_SUFFIX"],
        implementation_name = info["implementation_name"],
        actual_os = "@platforms//os:linux",
        python_version = "@rules_python//python/config_settings:is_python_{major}.{minor}.{micro}".format(**info),
    ))

local_runtime_repo = repository_rule(
    implementation = _local_runtime_repo_impl,
    doc = """\
Use a locally installed Python runtime as a toolchain implementation.

Note this uses the runtime as a *platform runtime*. A platform runtime is one where
the runtime is assumed to be part of the system targets run on. This means
targets don't include the runtime itself as part of their runfiles or inputs.
Instead, users must assure that where the targets run have the runtime
pre-installed or otherwise available.
""",
    attrs = {
        "interpreter_path": attr.string(
            doc = """\
An absolute path or program name on the `PATH` env var.

Note that, when a plain program name is used, the path to the interpreter is
resolved at repository evalution time, not runtime of any resulting binaries.
""",
        ),
    },
    environ = ["PATH", REPO_DEBUG_ENV_VAR],
)

def resolve_interpreter_path(rctx_or_mctx, ctx_attr, required = True):
    """Find the absolute path for a repo or module ctx interpreter.

    Args:
        rctx_or_mctx: A repository_ctx or module_ctx object
        ctx_attr: The `attr` struct.

    Returns:
        A path object or None. The path may not exist.
    """
    if "/" not in ctx_attr.interpreter_path:
        interpreter_path = rctx_or_mctx.which(ctx_attr.interpreter_path)
    else:
        interpreter_path = rctx_or_mctx.path(ctx_attr.interpreter_path)

    return interpreter_path
