workspace(name = "rules_python_custom_py_project_example")

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip",
    envsubst = ["PIP_RETRIES"],
    extra_pip_args = ["--retries=${PIP_RETRIES:-5}"],
    python_interpreter_target = "@python39_host//:python",
    requirements_lock = "//:requirements.txt",
)

load("//:requirements.bzl", "install_deps")

install_deps()
