workspace(name = "pip_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "778197e26c5fbeb07ac2a2c5ae405b30f6cb7ad1f5510ea6fdac03bded96cc6f",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
)

load("@rules_python//python/legacy_pip_import:pip.bzl", "pip_import", "pip_repositories")

pip_repositories()

pip_import(
    name = "helloworld_deps",
    requirements = "//helloworld:requirements.txt",
)

load("@helloworld_deps//:requirements.bzl", _helloworld_install = "pip_install")

_helloworld_install()

pip_import(
    name = "boto_deps",
    requirements = "//boto:requirements.txt",
)

load("@boto_deps//:requirements.bzl", _boto_install = "pip_install")

_boto_install()

pip_import(
    name = "extras_deps",
    requirements = "//extras:requirements.txt",
)

load("@extras_deps//:requirements.bzl", _extras_install = "pip_install")

_extras_install()
