workspace(name = "pip_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
)

load("@rules_python//python/legacy_pip_import:pip.bzl", "pip_import", "pip_repositories")

pip_repositories()

pip_import(
    name = "boto_deps",
    requirements = "//boto:requirements.txt",
)

load("@boto_deps//:requirements.bzl", _boto_install = "pip_install")

_boto_install()

pip_import(
    name = "extras_deps",
    requirements = "//extras:requirements.txt",
)

load("@extras_deps//:requirements.bzl", _extras_install = "pip_install")

_extras_install()
