workspace(name = "example_repo")

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(
    requirements = "//:requirements.txt",
)
