workspace(name = "py_import")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# XXX 0.0.3 doesn't include py_import.  Need to bump to a later release.
http_archive(
    name = "rules_python",
    sha256 = "e46612e9bb0dae8745de6a0643be69e8665a03f63163ac6610c210e80d14c3e4",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.3/rules_python-0.0.3.tar.gz",
)

load("@rules_python//python:pip.bzl", "pip_import", "pip_repositories")

pip_repositories()

pip_import(
    name = "examples_py_import",
    requirements = "//:requirements.txt",
)

load("@examples_py_import//:requirements.bzl", "pip_install")

pip_install()
