workspace(name = "py_import")

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python:pip.bzl", "pip_install")

pip_install(requirements = "//:requirements.txt")
