local_repository(
    name = "rules_python",
    path = "../../..",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

load("@rules_python//python:repositories_deps.bzl", "py_repositories_deps")

py_repositories_deps()

python_register_toolchains(
    name = "python_3_11",
    python_version = "3.11",
)
