workspace(name = "pip_parse_tests")

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

python_register_toolchains(
    name = "python3_9",
    python_version = "3.9",
)

load("@python3_9//:defs.bzl", "interpreter")
load("@rules_python//python:pip.bzl", "pip_parse")

# For a more thorough example of `pip_parse`. See `@rules_python//examples/pip_parse`
pip_parse(
    name = "pypi",
    incompatible_generate_aliases = False,
    python_interpreter_target = interpreter,
    requirements_lock = "//:requirements_lock.txt",
    requirements_windows = "//:requirements_windows.txt",
)

load("@pypi//:requirements.bzl", install_regular_deps = "install_deps")

install_regular_deps()

pip_parse(
    name = "pypi_aliases",
    incompatible_generate_aliases = True,
    python_interpreter_target = interpreter,
    requirements = "//:requirements_lock.txt",
    requirements_windows = "//:requirements_windows.txt",
)

load("@pypi_aliases//:requirements.bzl", install_alias_deps = "install_deps")

install_alias_deps()
