workspace(name = "rules_python_multi_python_versions")

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python/pip_install:repositories.bzl", "pip_install_dependencies")

pip_install_dependencies()

load("@rules_python//python:repositories.bzl", "python_register_multi_toolchains")

default_python_version = "3.9"

python_register_multi_toolchains(
    name = "python",
    default_version = default_python_version,
    python_versions = [
        "3.8",
        "3.9",
        "3.10",
    ],
)

load("@python//:pip.bzl", "multi_pip_parse")

multi_pip_parse(
    name = "pypi",
    default_version = default_python_version,
    requirements_lock = {
        "3.10": "//requirements:requirements_lock_3_10.txt",
        "3.8": "//requirements:requirements_lock_3_8.txt",
        "3.9": "//requirements:requirements_lock_3_9.txt",
    },
)

load("@pypi//:requirements.bzl", "install_deps")

install_deps()
