workspace(name = "rules_python_pypi_install_example")

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

load("@rules_python//python/pip_install:repositories.bzl", "pip_install_dependencies")

pip_install_dependencies()

python_register_toolchains(
    name = "python39",
    python_version = "3.9",
)

load("@python39//:defs.bzl", "interpreter")
load("@rules_python//python:pypi.bzl", "pypi_install")

pypi_install(
    name = "pypi_install",
    # Use fully resolved labels so that they're not accidentally interpreted as
    # repo-relative.
    # TODO(phil): Add test to make sure that the config settings are mutually
    # exclusive.
    pip_installation_report = [
        "//:intermediate_file_x86_64_linux.json",
        "//:intermediate_file_aarch64_linux.json",
    ],
)

load("@pypi_install//:packages.bzl", "load_pypi_packages")

load_pypi_packages(
    name = "pypi",
)

register_toolchains(
    "//cc:linux_toolchain_definition",
)
