workspace(name = "rules_python_pypi_install_example")

local_repository(
    name = "rules_python",
    path = "../..",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_multi_toolchains")

py_repositories()

load("@rules_python//python/pip_install:repositories.bzl", "pip_install_dependencies")

pip_install_dependencies()

python_register_multi_toolchains(
    name = "python",
    default_version = "3.10",
    python_versions = [
        "3.10",
        "3.11",
    ],
)

load("@rules_python//python:pypi.bzl", "pypi_install")

pypi_install(
    name = "pypi_install",
    # Use fully resolved labels so that they're not accidentally interpreted as
    # repo-relative.
    # TODO(phil): Add test to make sure that the config settings are mutually
    # exclusive.
    pip_installation_report = [
        "//:intermediate_file_py310_linux_x86_64.json",
        "//:intermediate_file_py310_linux_aarch64.json",
        "//:intermediate_file_py311_linux_x86_64.json",
        "//:intermediate_file_py311_linux_aarch64.json",
    ],
)

load("@pypi_install//:packages.bzl", "load_pypi_packages")

load_pypi_packages(
    name = "pypi",
)

register_toolchains(
    "//cc:linux_toolchain_definition",
)
